---
title: "4ª Lista de Exercícios"
author:
- Eniedson Fabiano Pereira da Silva Junior - 119110512
- João Paulo Alves Dantas - 119210258
- Rodrigo Farias Oliveira - 118110711
output:
  html_document: default
  pdf_document: default
---

```{css, echo=FALSE}
h1 {
  text-align: center;
  margin-bottom: 3rem;
}

img {
  text-align: center;
}
```

# Respostas

1.
a)
``` {r, echo=FALSE}
mean <- 100
desv <- 10

pnorm(110, mean = mean, sd = desv) - pnorm(90, mean = mean, sd = desv)
```

b)
``` {r, echo=FALSE}
mean <- 100
individuos <- 16
desv <- (10*10) / individuos 

pnorm((110-mean)/sqrt(desv)) - pnorm((90-mean)/sqrt(desv))
```

c)  

``` {r, echo=FALSE}
x <- seq(60, 140, length=120)

y1 <- dnorm(x, mean = 100, sd = 10)

y2 <- dnorm(x, mean = 100, sd = sqrt(100/16))

df <- data.frame(x,y1,y2)

suppressMessages(require(ggplot2))

g <- ggplot(df, aes(x))
g <- g + geom_line(aes(y=y1, colour="N(100,100)"))
g <- g + geom_line(aes(y=y2, colour="N(100,100/16)"))
g <- g + ylab("Y") + xlab("X")
g <- g + scale_colour_manual("", 
                      breaks = c("N(100,100)", "N(100,100/16)"),
                      values = c("red", "green"))
g


```

d)
``` {r, echo=FALSE}
valor <- qnorm(0.975)
((valor * sqrt(100))/10) ^ 2

```

2. 
a)
```{r, echo=FALSE}
normN <- qnorm(0.1)


mean <- (- 1) * ((normN * 10) - 500)
mean
```

b)
```{r, echo=FALSE}
normN <- qnorm(0.1)


mean <- (- 1) * ((normN * 10) - 500)

esperado <- 2000
individuos <- 4
variancia <- 100

mediaEsperada <- esperado/individuos

valor <- (mediaEsperada - mean) / sqrt(variancia/individuos)

pnorm(valor)

```

3.

4. 
``` {r}

p <- 0.1

pcorte <- 0.15

n <- 20

varr <- sqrt(p * (1 - p) / n)

pbarra <- (pcorte - p) / varr

1 - pnorm(pbarra)
```

5.
a)
``` {r}
probExata <- 0

for (defeitos in 0:10){
  probExata <- probExata + (choose(100,defeitos) * 0.1^defeitos * 0.9^(100-defeitos))
}

1 - probExata


pAprox <- 0.1

n <- 100

desvio <- pAprox * (1 - pAprox) / n

pnorm(0.1, mean=pAprox, sd=desvio)
```

b)
``` {r}
choose(100,0) * 0.1^0 * 0.9^100
```

6.
``` {r}

custo <- 3500

media <- 120

desvio <- 50

individuos <- 30

prob <- ((custo / individuos) - media)/(desvio/sqrt(individuos))

1 - pnorm(prob)
```

7.